### ISSUE TITLE
StyleCop rules

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/Proposals#16]
Is there currently an open-source effort to implement the StyleCop rules using analyzers? If not, it might be interesting to start one here.

Since this is a specific duplication of the functionality of a group of previously-defined analyzers, it would likely make sense to implement them within a single repository.

**Comment by tugberkugurlu** [comment]
Let's start up a repo (something called StyleCopAnalyzers or anything smilar maybe?) here and people can send PRs on each diagnostic separately. How does that sound?

Personally, I would like to implement a few of them.

**Comment by sharwell** [comment]
I wanted to check and see if this was being implemented anywhere else before starting over. Do you know of any?

**Comment by tugberkugurlu** [comment]
Nope. I also saw this today: https://twitter.com/Pilchie/status/533341247360888833

**Comment by sharwell** [comment]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers

**Comment by tugberkugurlu** [comment]
:+1:
