### ISSUE TITLE
Can we put diagnostic proposals here?

### ISSUE THREAD

**Issue by tugberkugurlu** [DotNetAnalyzers/Proposals#2]
I can see from the org name and this repo's readme that this place is intended for analyzers. Can we put diagnostic code fix proposals here? 

> Confession: I'm not sure if diagnostic code fix thing and analyzers are the same thing :smile:

**Comment by sharwell** [comment]
Absolutely! Analyzers is just the name of these extensions as they show in Solution Explorer.

**Comment by MarkMichaelis** [comment]
You can also put refactoring functionality here.
