### ISSUE TITLE
Sandcastle Help File Builder diagnostics

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/Proposals#22]
There are many opportunities for SHFB diagnostics, including the following.

Note: these are SHFB-specific _additions_ to the items in #21.
- Identify the use of language specific keywords, such as `null`, within XML documentation comments and suggest changing them to their language-independent form (in this case, `<see langword="null"/>`).
- Identify cases where override references (starting with `O:`) do not resolve.
- Identify cases where a `<conceptualLink>` does not resolve to a known target.
- Identify cases where `<token>` does not resolve to a known token.
- Identify `<see href="">` or `<seealso href="">` is missing the target URI

**Comment by BillWagner** [comment]
Well, is Sandcastle still supported?  It's looked quite abandoned for some time.

Note: I do like Sandcastle, and I would like to see it supported. It just doesn't look like much is happening there.

**Comment by sharwell** [comment]
I've been doing a lot of work on the project [here on GitHub](https://github.com/tunnelvisionlabs/SHFB). Many of my changes have been incorporated into the official project now. For an example of the current output, [see this page](http://openstacknetsdk.org/docs).

**Comment by sharwell** [comment]
> Identify the use of language specific keywords ...

Moved to DotNetAnalyzers/DocumentationAnalyzers#5 and DotNetAnalyzers/DocumentationAnalyzers#6.

> Identify cases where override references (starting with O:) do not resolve.

Moved to DotNetAnalyzers/DocumentationAnalyzers#8

> Identify cases where a `<conceptualLink>` does not resolve to a known target.

Moved to DotNetAnalyzers/DocumentationAnalyzers#11

> Identify cases where `<token>` does not resolve to a known token.

Moved to DotNetAnalyzers/DocumentationAnalyzers#12

> Identify `<see href="">` or `<seealso href="">` is missing the target URI

Moved to DotNetAnalyzers/DocumentationAnalyzers#13
