### ISSUE TITLE
Suggest using ConfigureAwait(false)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/Proposals#26]
This isn't fully fleshed out yet, but it would be nice to be able to identify cases where `ConfigureAwait(false)` definitely applies, and add it.

A refactoring could be provided for manual addition of the call in cases where code analysis was inconclusive.

**Comment by tugberkugurlu** [comment]
At first glance, diagnostic could be very tricky to suggest at the correct places as you need to be knowing the context of the code which is being executed.

I'm more for refactoring for this one.

**Comment by sharwell** [comment]
Moved to DotNetAnalyzers/AsyncUsageAnalyzers#4.
