### ISSUE TITLE
Define constant for string literal

### ISSUE THREAD

**Issue by AdamSpeight2008** [DotNetAnalyzers/Proposals#28]
Idea "borrowed" from this Roslyn [Issue](https://roslyn.codeplex.com/workitem/338)

``` c#
public void Something() {
    db.Where(c=> c.Name == "bart");
}
```

after the code-fix.

``` c#
private const readonly string Bart = "bart";
public void Something() {
    db.Where(c=> c.Name == Bart);
}
```

**Comment by sharwell** [comment]
@Bartmax I would ask Lucian Wischik (@ljw1004) for his MVVM code fix that suggests replacing an inline `new PropertyChangedEventArgs(nameof(Property))` with a new field that is referenced instead. The code for this feature would probably look quite similar.

**Comment by ljw1004** [comment]
My code fix is here... https://github.com/ljw1004/dotnet-code-analyzer/blob/master/dotnet-code-analyzer/Analyzer_XamlAppTips/UseStaticChangedCS.vb

**Comment by Bartmax** [comment]
@ljw1004 wish I understand 10% of that code :(

**Comment by sharwell** [comment]
@Bartmax Is the issue the use of Visual Basic, or the use of the .NET Compiler Platform APIs?

**Comment by Bartmax** [comment]
I never did anything with .NET Compiler Platform API (I didn't even know it was called like that). Used to called CodeAnalysis namespace :)

Guess got a lot to read, but can't help much here right now.
