### ISSUE TITLE
Possibility of moving repo here?

### ISSUE THREAD

**Issue by ErikEJ** [DotNetAnalyzers/Proposals#34]
Would it be possible to move this repo here? https://github.com/ErikEJ/TSqlAnalyzer

**Comment by sharwell** [comment]
Hi @ErikEJ,

I sent you an invitation to join the **DotNetAnalyzersStaging** organization. If you move your repository there, then I can move it here and set up the permissions for you to have access to it again.

:smile:

**Comment by ErikEJ** [comment]
@sharwell  Great - Move Done!

**Comment by sharwell** [comment]
And done :+1: 

You'll probably want to fork the repository back to your account before you continue working, but you shouldn't have to make any changes to your working copy.

https://github.com/DotNetAnalyzers/TSqlAnalyzer
