### ISSUE TITLE
Suggest null guards for reference type parameters

### ISSUE THREAD

**Issue by tugberkugurlu** [DotNetAnalyzers/Proposals#4]
When a method or constructor accepts reference type parameters, it's most of the time the case to check against `null` and throw `ArgumentNullException`. 

The analyzer can suggest to put the guard as below (at the top of the method body):

``` csharp
public string GetBar(string value)
{
    if(value == null)
    {
        throw new ArgumentNullException(nameof(value));
    }

    // ...
}
```

In case there are multiple reference type parameters, it should be able to put the guard into right place. For example, value should be first and value2 should be second guard below:

``` csharp
public string GetBar(string value, string value2)
{
    if(value == null)
    {
        throw new ArgumentNullException(nameof(value));
    }

    if(value2 == null)
    {
        throw new ArgumentNullException(nameof(value2));
    }

    // ...
}
```

**Comment by AdamSpeight2008** [comment]
I think it should only suggest this when a method parameter doesn't already have a guard.
Also Null isn't always an error or a mistake. It just indicates that (for reference types) that it doesn't point to an instance of that type.

**Comment by tugberkugurlu** [comment]
> I think it should only suggest this when a method parameter doesn't already have a guard.

 :+1: for this.

> Also Null isn't always an error or a mistake. It just indicates that (for reference types) that it doesn't point to an instance of that type.

I agree. I was thinking for an hidden analyzer but I now think it should be a refactoring instead of an analyzer. I wasn't aware of the difference when I opened up this issue but I now see that there is a special class for refactoring: `CodeRefactoringProvider`.

Do you guys aggregate refactoring proposals here, too?

**Comment by sharwell** [comment]
@tugberkugurlu I think refactorings could be just as beneficial here as anything else we are working on. :smile:

**Comment by tugberkugurlu** [comment]
@sharwell nice! I was thinking the same. 

OTOH, (while being not sure) the name of the organization seems a little off if the distinction between refactoring and analyzer is big in roslyn world.

**Comment by sharwell** [comment]
**Analyzers** is the name of the node in Solution Explorer where all of these items appear. The command in Visual Studio to add a new one to the project is **Add Analyzer...**.

I'm _hoping_ the accepted terminology becomes:
- **Diagnostic**: Code which performs a source or binary analysis to identify potential problems and/or "items of interest" to a developer.
- **Code fix**: Code which performs an automatic alteration to the source or binary in response to the output of a Diagnostic.
- **Refactoring**: Code which performs on-demand alteration to the source or binary in response to a direct request from the developer, which may or may not be prompted by the output of a Diagnostic.
- **Analyzer**: Any of the above, or any logical combination of the above.

**Comment by tugberkugurlu** [comment]
@sharwell :+1: sounds very logical. Thanks for the explanation.

**Comment by MarkMichaelis** [comment]
@tugberkugurlu note that a null value could be correct (meaning no guard is needed).  Therefore, I expect this needs to be built as a refactor rather than a code analyzer and only when there is no guard already in place.

**Comment by tugberkugurlu** [comment]
@MarkMichaelis yes, I agree as already stated in my [previous](https://github.com/DotNetAnalyzers/Proposals/issues/4#issuecomment-63229176) [comments](https://github.com/DotNetAnalyzers/Proposals/issues/4#issue-48916904).

**Comment by MarkMichaelis** [comment]
Sorry... I didn't understand that.  Sounds like we are on the same page.

**Comment by AdamSpeight2008** [comment]
You could set the Warning level to Information in the diagnostic. This way it isn't an error / warning.
`This parameter has no guard. Is this correct?` with a code-fix to implement if they want to.

**Comment by sharwell** [comment]
@AdamSpeight2008 For something like this (where a high rate of false positives is likely), even an Information level diagnostic could be irritating because it would flood the Errors list with messages.

**Comment by tugberkugurlu** [comment]
@AdamSpeight2008 I do think that it should be refactoring. If it's going to be an diagnostic analyzer, it should have `DiagnosticSeverity` as `Hidden`. Otherwise, it would be annoying :smile:

**Comment by tugberkugurlu** [comment]
BTW, I started prototyping (mainly trying to figure out where should I touch and what I should do :smile: ) https://github.com/tugberkugurlu/NullGuarRefactoring-temp/blob/master/CodeRefactoring2/CodeRefactoring2/CodeRefactoringProvider.cs

**Comment by tugberkugurlu** [comment]
@sharwell can we open up a repository for this? Name could be **NullParameterCheckRefactoring**?

I'm nearly done with getting it working OK. I wanna tidy it up and push to straight a repo here if possible. What do you think?

![screenshot 2014-11-17 13 01 02](https://cloud.githubusercontent.com/assets/328122/5068702/e2222500-6e59-11e4-86c7-dffdbfb96516.png)

**Comment by sharwell** [comment]
Done

https://github.com/DotNetAnalyzers/NullParameterCheckRefactoring

**Comment by AdamSpeight2008** [comment]
Sam, 

 I consider this half done, since it also applicable to vb.net.

-Adam

**Comment by sharwell** [comment]
@AdamSpeight2008 The proposal is marked complete when someone _starts_ working on the code for the feature. You would normally file an issue on that project requesting support for VB, but in this case it's already been done (DotNetAnalyzers/NullParameterCheckRefactoring#6).
