### ISSUE TITLE
VB.net?

### ISSUE THREAD

**Issue by AdamSpeight2008** [DotNetAnalyzers/Proposals#5]
Are VB.net analysers welcome? Both written in and or target VB.net

**Comment by sharwell** [comment]
Short answer: Yes, definitely.

Long answer:

At this time, we welcome proposals for any analyzers which are meant to be implemented using the .NET Compiler Platform (aka Roslyn). In the future, we may extend this to support analyzers for any languages targeting the CLR as a runtime environment, and/or languages incorporated into Visual Studio (all of this TBD).
