### ISSUE TITLE
Single Analyzer per Project or Multiple Analyzers in a Single Project?

### ISSUE THREAD

**Issue by MarkMichaelis** [DotNetAnalyzers/Proposals#7]
@tugberkugurlu: There is a strategy here that I am not sure we have discussed.  I was expecting we would have analyzer projects with multiple analyzers in them so that only a single install/nuget package is required and the ruleset determines which ones are active or not.  The point being I don't want to have to reference nuget packages for each and every rule - this was actually the impetus for creating the project (otherwise they could all just be kept on nuget individually).

Thoughts?

New thread following on "Replace var with explicit type" discussion:

**Comment by sharwell** [comment]
Whether the analyzers are distributed via NuGet or as VSIX files, it's easy to create a "metadata-only" package that "bundles" multiple items together. For example, you could create a NuGet package called **MarkMichaelis.FavoriteAnalyzers** which doesn't contain any content, but simply includes a `<dependencies>` element which references the NuGet packages of all the analyzers you want to have included in the project.

I wasn't suggesting every diagnostic have its own NuGet package, but I do find that for every group of diagnostics someone proposes, I'm hesitant about the behavior perhaps half of them. At least until such time as clear best practices are established, finer granularity seems to be the option most suited to the very diverse needs of .NET developers.

**Comment by MarkMichaelis** [comment]
@sharwell: good point regarding nuget packages, but don't we still have the problem with vsix?  
I agree with you regarding the concern that too many of the analyzers are controversial.  However, don't you think that if we agree on a set as being useful and not controversial, we can get those combined together.  As we get lots, we can group them.
The others, we can group together as well (I don't have a name) but with them all off by default, developers who utilize them could turn them on as needed.

**Comment by MarkMichaelis** [comment]
Another point in favor of keeping them separate (if any were on by default) is that once a set is "released" it not be reasonably possible to add any, at least ones that are more than informational, since doing so would be a code breaking change.
Still, I would like to see v1.0 with a minimal set that we all agree on. As a minimum, I can imagine a set of refactorings and analyzers that we can all agree on without too much difficulty.  
For examples:
Refactoring:
- class into its own file
- member set into base class
- ...

Analyzers:
- turn C# 1.0 delegate invocation to use 6.0 syntax (hidden)
- null propagation on indexers that throw exceptions (warning)
- throw the caught exception rather than the empty throw (still allowing an alternate throw)
- non-standard naming conventions on public methods (possible excepting those that are test methods)
- ...

Obviously... I am not even attempting to create any sort of comprehensive list.  My point being, I think we could come up with a list that isn't controversial.  (of course, you may not like the rules I have proving me wrong :)

**Comment by sharwell** [comment]
Considering the way diagnostic analyzers are registered, I'm not sure disabling individual diagnostics implies they will not have a performance impact on the compiler and/or IDE. As a developer with abnormally high performance demands, I would be looking for the following two things:
- I wouldn't want any disabled diagnostic to have a negative performance impact on the compiler or IDE functionality.
- Even if I agreed with the results of a custom diagnostic, if the performance overhead was perceived to be too great I would not want it always enabled. This is a very subjective measure, so even if everyone agreed that a particular set of say 10 diagnostics were particularly high-quality, some users still might not want to include all 10.

For now, I think we should focus on creating individual analyzers which are particularly accurate and perform will for targeted tasks. As these become more complete, we could consider aggregating sets of them into bundles targeted towards particular audiences (e.g. desktop applications, web applications, etc.).

**Comment by AdamSpeight2008** [comment]
As along as you keep vsix id the same and change the version, it will appear as an update. 

You kniw what could be good idea is to have Analyser gallery, and in VS add it as an additional  location where extension can be ibstalled from.

**Comment by sharwell** [comment]
By the way, a VSIX can bundle multiple other VSIX files. Case in point - the following extension's _only_ purpose is to simplify the installation of [currently] two other Visual Studio extensions as one step.

https://visualstudiogallery.msdn.microsoft.com/fca95a59-3fc6-444e-b20c-cc67828774cd

**Comment by MarkMichaelis** [comment]
This is well established ground as it is leveraging the VS Premium
functionality of the past.  I am fairly confident there should not be any
noticeable performance impact for analyzers that are not enabled.

Thanks,
Mark

**Comment by AdamSpeight2008** [comment]
Also what's wrong with having controversial ones? Who decides what is or isn't controversial? 

Another rule should be if an analyzer is suitable for both languages C# and VB, both langiage must be supportted. (My do).

A possible set could! VB6 coding patterns with VB.net pattern codefixes.

**Comment by MarkMichaelis** [comment]
Hi Adam,

There is nothing wrong with controversial ones.  I was under the assumption
that there was going to be a fundamental set that we all agreed on and
those that we didn't agree on would be off by default.

Controversial: The ones that we expect or experience considerable
disagreement as to whether they are valid or not.
Who decides: The community of course... with the owners to make final
arbitration - like any OSS project. :)

Thanks,
Mark

**Comment by sharwell** [comment]
I suggest sending a pull request with changes to the README.md and/or another document within this repository to provide guidance for developing analyzers with an appropriate level of granularity. If you are using the built-in Markdown editor, make sure to fork the repository to your account prior to editing the file or it will commit the changes immediately (without allowing you to make a pull request for review).

I'm marking this as closed (answered), but I'll gladly reopen it if someone believes I did so too early.

**Comment by AdamSpeight2008** [comment]
What's the guidance for merged VSIXs that contain multiple analysers? For example NullParameterCheckRefactoring has now C# and VB support.
The individual creators are not accredited for there contribution just DotNetAnalyser.

**Comment by sharwell** [comment]
That's up to the project authors to decide. If you have a concern or suggestion, you can open an issue on the project issue tracker. I don't expect there to be an unresolvable problem with this (at least for now).

**Comment by BillWagner** [comment]
I'd like to consider making some of the diagnostics registered as refactorings instead (case in point: the code fix to replace var with an explicit type). It doesn't fix a problem, but it does change the readability of the code (some like it, some hate it).

I'd like to consider that we ask that diagnostics and code fixes be restricted to coding practices that can easily lead to bugs, rather than style issues.

**Comment by tugberkugurlu** [comment]
> I'd like to consider making some of the diagnostics registered as refactorings instead (case in point: the code fix to replace var with an explicit type). It doesn't fix a problem, but it does change the readability of the code (some like it, some hate it).

@BillWagner yes, I was thinking the same thing + I would like to provide the opposite functionality (replace explicit type with `var`) as a refactoring. The [var repo](https://github.com/DotNetAnalyzers/VarUsageAnalyzer) is not in the correct shape now but I will fix it very shortly.
