### ISSUE TITLE
Recursion Detector

### ISSUE THREAD

**Issue by AdamSpeight2008** [DotNetAnalyzers/Proposals#8]
This analyaer would check for recursive calls and if infinite recursion is possible, warn the user. Eg Missing base case.

**Comment by sharwell** [comment]
The case I would _really_ want to see is this:

``` csharp
public int Foo { get { return this.Foo; } }
```

Currently it's way too easy to miss the above if you meant this:

``` csharp
public int Foo { get { return this.foo; } }
```

**Comment by AdamSpeight2008** [comment]
This look very close to what Mis-Assignment In Constuctors does. So that code could used as a base for this.
